source $HOME/.profile

# History
setopt append_history
setopt share_history
setopt hist_save_no_dups
SAVEHIST=1000
HISTSIZE=1000
HISTFILE=~/.history

fpath=($(brew --prefix)/share/zsh/site-functions $fpath)
fpath=($(brew --prefix)/share/zsh-completions $fpath)

zstyle ':completion:*' completer _complete
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' '+l:|=* r:|=*'
zstyle ':completion:*' rehash true
autoload -Uz compinit && compinit -i
autoload -U bashcompinit && bashcompinit

export PS1="%{%F{blue}%}%n%{%F{cyan}%}@%{%F{green}%}%m%{%F{cyan}%}:%{%F{red}%}%~%{%F{cyan}%} $ %{%f%}"

alias ls='ls --color=auto -pF'
alias ll='ls -alFh'
alias bc='bc -ql'

alias rm='rm -i'
alias m='make'
alias cm='cmake'
alias ccm='ccmake'

export EDITOR=vim
export CLICOLOR=1

# Make suppr and some other key working
bindkey "\e[3~" delete-char
bindkey ';5D' backward-word
bindkey ';5C' forward-word

# Interactive only setup
if [[ $- == *i* ]] then
    # Needed by the fancy .vimrc
    # stty -ixon sane
    
    unset LS_COLORS
    export RUST_NEW_ERROR_FORMAT=1
    fortune -s | cowthink
fi

